---
new_page_extension: md
auto_deploy: false
admin_path: "/static/editor"
webhook_url: 
sections:
- type: directory
  path: assets/content/pages
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: assets/content/blog
  label: Blog
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: document
  path: assets/content/site-options.json
  label: Site Options
upload_dir: katasite
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - GITHUB_TOKEN=b1ab6cd26e69efb63819bd4bfd9823452e6cdeff
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
